### ISSUE TITLE
Why 'train_val loader' is set to be 'all loader' ?

### ISSUE THREAD

**Issue by BUserName** [TencentARC/SFDA#2]
Thanks for your excellent work and for sharing the code with us!

Just want to double check, in line 46 of 'forward_feature_group1.py', why should be set train_val loader to be all loader? 

Will that cause potential test data leakage? Please kindly correct me if I missed anything. Thanks again!

**Comment by wqshao126** [comment]
Thanks for your interest in our work. In this work, we set the target data to be all data consisting of both train_loader and val_loader for all downstream tasks. For fair comparison, we also reimplemented previous techniques such as LEEP and LogME using all data.

**Comment by BUserName** [comment]
Thanks for your clarification.
