### ISSUE TITLE
all sfda_score == 1.0

### ISSUE THREAD

**Issue by Fay-why** [TencentARC/SFDA#5]
hello, dear author, thanks for your great work.
I used your sfda code in the parc framework(I bet you know, because it is in your readme file.).  As you know, this framework only use 500 samples every dataset to calculate the estimation score. I found all the sfda scores turned into 1.0, and when I use the pca reduction to make the forward features(origin 2024d) to 32d before I calculated sfda score, it seems well.

Can you tell me the reason about it? I am so confused about that...

**Comment by wqshao126** [comment]
Hi, thanks for your interest. Basically, if you obtain a score exactly equal to 1.0, it means that our sfda can correctly classify all examples. Such a case happens only if the target dataset is very easy to be classified from my experience. In this case, you can try to adjust the strength of ConfMix noise which can make the classification harder. It would be an alternative to differentiate pre-trained models. Looking forward to your results.

**Comment by Fay-why** [comment]
Thanks for your reply!

Maybe the origin forward features dimension 2024d is too high for this situation which only using 500 sampls to calculate SFDA, leading to a weired "overfitting" results...

By the way, have you ever used the dimension reduction method, like PCA, in your expriments?

**Comment by wqshao126** [comment]
We do not use any dimension-reduction methods, as we found that it is too slow to perform PCA on the whole target dataset. This is also why NLEEP is slower than other methods.
